### PR TITLE
test: Use before() blocks

### PR DESCRIPTION
**Pull request by Turbo87**
This way failures in the code won't crash mocha, but will instead fail all depending tests

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by Turbo87** [comment]
@caridy could you have a quick look at this as well?

**Comment by caridy** [comment]
I have no objections. But I don't really like defensive code in tests, if they fail, we fix it, that's all. I will let @ericf to decide this, he was the one writing those tests.

**Comment by Turbo87** [comment]
@caridy the tests will still fail, but it is easier to trace it back to *what* actually failed.

**Comment by Turbo87** [comment]
@ericf any comments?

**Comment by caridy** [comment]
@ericf and I discussed this few days ago, we think the first block is ok (the first before call), but the rest are unnecessary defensive code in tests in our opinion. If you can update the PR I can merge it.

**Comment by Turbo87** [comment]
@caridy converting just the first block does not seem to work (see https://travis-ci.org/yahoo/formatjs-extract-cldr-data/jobs/71211246). 

I assume that mocha first executes all `describe()` blocks before starting any tests and the corresponding `before()` blocks. In other words: `var field = data.en.fields[...];` in the `describe()` block is executed before `data` is assigned in the `before()` block above.

**Pull request closed without merging**
